
MQTT_BROKER_URL = 'broker.hivemq.com'
MQTT_BROKER_PORT = 1883
MQTT_USERNAME = ''
MQTT_PASSWORD = ''
MQTT_KEEPALIVE = 60
MQTT_TLS_ENABLED = False


MONGODB_DB ='ZC'
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017

